# Site settings
title: Singlethread Blog
email: jaycorpinc@gmail.com
description: Stuff regarding things
baseurl: ""
url: ""
paginate: 4
paginate_path: "/blog/page/:num/"

# Social links
facebook: username
twitter: username
instagram: username
google_plus: username
github: jaycorp
disqus: jaycorp

# Build settings
markdown: kramdown
permalink: pretty
gems: [jekyll-paginate]
rouge: pygments
