# Site settings
title: jayCorp
email: jaycorpinc@gmail.com
description: Stuff regarding things
baseurl: ""
url: ""
paginate: 4
paginate_path: "page/:num/"

# Social links
facebook: username
twitter: username
instagram: username
google_plus: username
github: username
disqus: username

# Build settings
markdown: kramdown
permalink: pretty
gems: [jekyll-paginate]
rouge: pygments
